import { describe, it, expect } from "vitest";
import { parseYarnLockfile, parsePnpmLockfile } from "../../src/tools/analysis.js";

describe("Extended Lockfile Parsers (Phase 2)", () => {
  it("should parse Yarn v1 lockfile format", () => {
    const yarnContent = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.
# yarn lockfile v1

"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.12.13":
  version "7.12.13"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.13.tgz"
  dependencies:
    "@babel/highlight" "^7.12.13"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`;

    const parsed = parseYarnLockfile(yarnContent);

    expect(parsed.size).toBe(2);
    expect(parsed.has("@babel/code-frame")).toBe(true);
    expect(parsed.get("@babel/code-frame")?.version).toBe("7.12.13");
    expect(parsed.has("lodash")).toBe(true);
    expect(parsed.get("lodash")?.version).toBe("4.17.21");
  });

  it("should parse pnpm lockfile format", () => {
    const pnpmContent = `
lockfileVersion: '6.0'

settings:
  autoInstallPeers: true

packages:

  /@babel/code-frame@7.12.13:
    resolution: {integrity: sha512-foo}

  /lodash@4.17.21:
    resolution: {integrity: sha512-bar}
`;

    const parsed = parsePnpmLockfile(pnpmContent);

    expect(parsed.size).toBe(2);
    expect(parsed.has("@babel/code-frame")).toBe(true);
    expect(parsed.get("@babel/code-frame")?.version).toBe("7.12.13");
    expect(parsed.has("lodash")).toBe(true);
    expect(parsed.get("lodash")?.version).toBe("4.17.21");
  });
});
